### ISSUE TITLE
shared/keypad/keypad.properties

### ISSUE THREAD

**Issue by scivola** [mozilla-japan/gaia-l10n#1]
> asterisk.ariaLabel=アスタリスク
> hashSign.ariaLabel=ハッシュ記号

これは「＊」「＃」ボタンのことだと思いますが，電話業界では「＊」は「スター」ではないかと思います。
「＃」が「ハッシュ記号」で通じる日本人はプログラマーだけかもしれません。「ナンバー記号」が無難かと思います。ただ，電話の音声ガイダンスでは圧倒的に「シャープ」と呼ばれていますね（ナンバー記号とシャープは本来別物ですが）。

**Comment by marsf** [comment]
Wikipedia:
- [スターマーク](https://ja.wikipedia.org/wiki/%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%9E%E3%83%BC%E3%82%AF)
- [番号記号](https://ja.wikipedia.org/wiki/%E7%95%AA%E5%8F%B7%E8%A8%98%E5%8F%B7)

ITU-T 勧告:
- [E.161 : Arrangement of digits, letters and symbols on telephones and other devices that can be used for gaining access to a telephone network](http://www.itu.int/rec/T-REC-E.161-200102-I/en)

ITU-T E.161 では、「⚹」 は `The symbol will be known as the star or the equivalent term in other languages.`、「#」は `In some countries an alternative term (e.g. "hash", "pound" or "number sign") may be necessary for this
purpose, particularly where the form in Figure 4 is commonly used, in which case it is useful to select and
to recommend a preferred term for consistent use nationally.` とありました。

それぞれ、「スター」と「ナンバー記号」でよいですね。

**Comment by marsf** [comment]
v2_2 と v2_1 にも cherry-pick でコミットしました。
